/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/professional-projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all professional projects */
        get: operations["GetProfessionalProjects"];
        put?: never;
        /** Add a new professional project */
        post: operations["AddProfessionalProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/professional-projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a professional project by ID */
        get: operations["GetProfessionalProjectById"];
        /** Update an existing professional project */
        put: operations["UpdateProfessionalProject"];
        post?: never;
        /** Delete a professional project */
        delete: operations["DeleteProfessionalProject"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        professionalProject: {
            id?: string | null;
            name?: string | null;
            description?: string | null;
            developerCommentary?: string | null;
            marketingSiteUrl?: string | null;
            demoUrl?: string | null;
            screenshots?: string[] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    GetProfessionalProjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of professional projects */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["professionalProject"][];
                };
            };
        };
    };
    AddProfessionalProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The project to create */
        requestBody: {
            content: {
                "application/json": components["schemas"]["professionalProject"];
            };
        };
        responses: {
            /** @description The created project */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["professionalProject"];
                };
            };
            /** @description Invalid project data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetProfessionalProjectById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The requested project */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["professionalProject"];
                };
            };
            /** @description Project not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UpdateProfessionalProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project ID */
                id: string;
            };
            cookie?: never;
        };
        /** @description The updated project data */
        requestBody: {
            content: {
                "application/json": components["schemas"]["professionalProject"];
            };
        };
        responses: {
            /** @description The updated project */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["professionalProject"];
                };
            };
            /** @description Invalid project data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Project not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DeleteProfessionalProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Project not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
